config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("data/", include("data.urls", namespace="data")),
    path("events/", include("events.urls", namespace="events")),
    path("personnel/", include("personnel.urls", namespace="personnel")),
    path("prediction/", include("prediction.urls", namespace="prediction")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.go_to_home, name="home"),
]

data/urls.py
from django.urls import path
from . import views

app_name = "data"

urlpatterns = [
    path("my_department", views.get_my_departemnt, name="my-department",),
]

events/urls.py
from django.urls import path
from . import views

app_name = "events"

urlpatterns = [
    path("list/", views.EventListView.as_view(), name="list",),
    path("create/", views.EventCreateView.as_view(), name="create"),
    path("<int:pk>", views.EventDetailView.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EventEditView.as_view(), name="edit"),
    path("<int:pk>/delete/", views.delete_event, name="delete",),
    path("search", views.EventSearchView.as_view(), name="search",),
]

personnel/urls.py
from django.urls import path
from . import views

app_name = "personnel"


urlpatterns = [
    path("", views.PersonnelReportListView.as_view(), name="list"),
    path("create/", views.PersonnelReportCreateView.as_view(), name="create"),
    path("<int:pk>", views.PersonnelReportDetailView.as_view(), name="detail"),
    path("<int:pk>/edit/", views.PersonnelReportEditView.as_view(), name="edit"),
    path("<int:pk>/delete/", views.delete_personnel_report, name="delete",),
    path("summary/", views.PersonnelReportSummaryView.as_view(), name="summary",),
    path("graph/", views.update_graph, name="update-graph",),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login", views.LoginView.as_view(), name="login"),
    path("login/github", views.github_login, name="github-login"),
    path("login/github/callback", views.github_callback, name="github-callback"),
    path("login/kakao", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback", views.kakao_callback, name="kakao-callback"),
    path("logout", views.log_out, name="logout"),
    path("signup", views.SignUpView.as_view(), name="signup"),
    path("verify/<str:key>", views.complete_verification, name="complete-verification"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
]

templates/partials/footer.html
<footer class="container mx-auto text-center py-10 border-t font-medium text-gray-500 flex flex-col">
    <span>
        Please don't copy us
    </span>
    <span>&copy; 2020 IDA Corp. All rights reserved.</span>
</footer>

templates/partials/messages.html
{% if messages %}
<ul class="absolute top-0 mx-auto left-0 right-0 flex justify-center">
    {% for message in messages %}
    <li
        class="message font-medium bg-gray-700 z-40 rounded-full text-white py-4 px-6 w-3/12 text-center {% if message.tags %}{{message.tags}}{% endif %}">
        {{message}}</li>
    {% endfor %}
</ul>
{% endif %}

templates/partials/nav.html
<ul class="flex items-center text-sm font-medium h-full">

    {% if user.is_authenticated %}
    <li class="nav_link"><a href="{% url "prediction:summary" %}">안전전망</a></li>
    <li class="nav_link"><a href="{% url "personnel:summary" %}">인원보고</a></li>
    <li class="nav_link"><a href="{% url "events:list" %}">주요일정</a></li>
    <li class="nav_link"><a href="{% url "data:my-department" %}" class="text-gray-700 font-medium">My Department</a>
    </li>
    <li class="nav_link"><a href="{% url "users:profile" user.pk %}">Profile</a></li>

    <li class="nav_link"><a href="{% url "users:logout" %}">Log out</a></li>
    {% else %}
    <li class="nav_link"><a href="{% url "users:login" %}">Log in</a> </li>
    <li class="nav_link"><a href="{% url "users:signup" %}">Sign up</a> </li>
    {% endif %}
</ul>

templates/partials/social_login.html
<div class="flex flex-col w-full">
    <a href="{% url 'users:github-login' %}"
        class="btn border-2 text-gray-700 mb-2 border-gray-700 text-center rounded-sm py-5">
        <i class="fab fa-github-alt mr-2 fa-lg"></i>Continue with Github
    </a>
    <a href="{% url 'users:kakao-login' %}"
        class="btn border-2 text-yellow-800 mb-2 border-yellow-400 text-center rounded-sm py-5 bg-yellow-400">
        <i class="fas fa-comment mr-2 fa-lg"></i>Continue with kakao
    </a>
</div>

<div class="flex items-center w-full my-5">
    <div class="h-px w-full bg-gray-400"></div>
    <span class="text-gray-600 font-medium mx-4 text-sm">or</span>
    <div class="h-px w-full bg-gray-400"></div>
</div>