config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("data/", include("data.urls", namespace="data")),
    path("events/", include("events.urls", namespace="events")),
    path("personnel/", include("personnel.urls", namespace="personnel")),
    path("prediction/", include("prediction.urls", namespace="prediction")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.go_to_home, name="home"),
]

data/urls.py
from django.urls import path
from . import views

app_name = "data"

urlpatterns = [
    path("my_department", views.get_my_departemnt, name="my-department",),
]

events/urls.py
from django.urls import path
from . import views

app_name = "events"

urlpatterns = [
    path("list/", views.EventListView.as_view(), name="list",),
    path("create/", views.EventCreateView.as_view(), name="create"),
    path("<int:pk>", views.EventDetailView.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EventEditView.as_view(), name="edit"),
    path("<int:pk>/delete/", views.delete_event, name="delete",),
    path("search", views.EventSearchView.as_view(), name="search",),
]

data/models.py
from django.db import models
from django_countries.fields import CountryField
from core import models as core_models


# Collect Master Data Class


class Country(models.Model):

    """ Define countries that use """

    code = CountryField()
    korean = models.CharField(max_length=255)

    def __str__(self):
        return self.korean

    def name(self):
        return self.korean


class Department(core_models.TimeStampedModel):

    """ Define department ID """

    name = models.CharField(max_length=255)
    koica_code = models.CharField(max_length=255)
    location = models.ForeignKey(
        Country, related_name="departments", on_delete=models.PROTECT
    )
    is_active = models.BooleanField(verbose_name="Active", default=True)

    def __str__(self):
        return self.name

    def get_latest_prediction(self):
        if self.prediction.filter().order_by("-created"):
            return self.prediction.filter().order_by("-created")[0]
        else:
            return None

    def get_latest_personnel_report(self):
        if self.personnel.filter().order_by("-created"):
            return self.personnel.filter().order_by("-created")[0]
        else:
            return None

    def get_prediction(self):
        return self.prediction.filter().order_by("-created")

    def get_personnel_report(self):
        return self.personnel_report.filter().order_by("-created")


class DepartmentDetail(core_models.TimeStampedModel):

    """ Define Department details.
    When they update, actually, they create detail. """

    class Meta:
        verbose_name = "Department detail"

    department = models.ForeignKey(
        Department, related_name="department_detail", on_delete=models.PROTECT
    )
    address = models.TextField()
    countries = models.ManyToManyField(
        Country, related_name="department_detail", blank=True
    )
    description = models.TextField()
    antecedents = models.ManyToManyField(
        Department, related_name="antecedents", blank=True
    )
    active = models.BooleanField(default=False)

    def __str__(self):
        return self.department.name + " detail"


class Region(models.Model):
    name = models.CharField(max_length=255)
    countries = models.ManyToManyField(Country, related_name="regions", blank=True,)

    def __str__(self):
        return self.name

data/views.py
from django.http import Http404
from django.views.generic import View, ListView, FormView
from django.shortcuts import render, redirect, reverse
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from users import mixins as user_mixins
from . import models, forms

# Create your views here.


class HomeView(user_mixins.LoggedInOnlyView, ListView):

    model = models.Department
    context_object_name = "department"


def get_my_departemnt(request):
    
    department = request.user.department
    template_name = "data/department_detail.html"
    
    if department:
        return render(request, template_name, {'department': department})
    else:
        return redirect(reverse("users:update"))
        

templates/data/department_detail.html
{% extends "base.html" %}

{% block page_title %}
{{department.name}}
{% endblock page_title %}

{% block content %}

<div class="container mx-auto pb-10">

    <div class="justify-between flex mb-3">

        <div class='w-1/2 flex'>
            <a href="{% url 'prediction:create' %}" class="btn bg-red-500 my-0 mx-3 text-white">안전전망 작성</a>
            <a href="{% url 'prediction:list' %}" class="btn my-0 mx-3 text-red-500 font-bold">안전전망 전체목록</a>
        </div>
        <div class='w-1/2 flex'>
            <a href="{% url 'personnel:create' %}" class="btn bg-teal-500 my-0 mx-3 text-white">인원보고 작성</a>
            <a href="{% url 'personnel:list' %}" class="btn my-0 mx-3 text-teal-500 font-bold">인원보고 전체목록</a>
        </div>

    </div>

    <div class="flex">

        {% with department.get_prediction as prediction %}

        <div class="w-1/2 flex flex-wrap justify-center mb-10">
            {% for predict in prediction %}
            {% include 'mixins/prediction/predict_card.html' with predict=predict %}
            {% endfor %}
        </div>

        {% endwith %}

        <div class='border'></div>
        {% with department.get_personnel_report as personnel_report %}

        <div class="w-1/2 flex flex-wrap justify-center mb-10">
            {% for report in personnel_report %}
            {% include 'mixins/personnel/report_card.html' with report=report %}
            {% endfor %}
        </div>


        {% endwith %}

    </div>

</div>
{% endblock content %}

templates/data/department_list.html
{% extends "base.html" %}


{% block page_title %}
안전예보
{% endblock page_title %}

{% block content %}

<div class="container mx-auto pb-10">
    <div class="justify-between flex mb-3">
        <div class='w-1/2 flex'>
            <a href="{% url 'prediction:create' %}" class="btn bg-red-500 my-0 mx-3 text-white">신규작성</a>
        </div>
        <div class='w-full align-middle'>
            <div>
                <form method="get" action="{% url "prediction:search" %}" class="w-9/12 inline-block align-middle">
                    <input
                        class="search-box border inline-block align-middle px-5 w-full font-medium text-gray-900 placeholder-gray-600 py-3 rounded-sm w-64 shadow-md hover:shadow-lg focus:outline-none"
                        name="title" placeholder="Search by Title" />
                </form>
            </div>
        </div>
    </div>
    <div class="flex flex-wrap justify-center mb-10">
        {% for event in prediction %}
        {% include 'mixins/events/event_card.html' with event=event %}
        {% endfor %}
    </div>
    <div class="flex items-center justify-center mx-auto container">
        {% if page_obj.has_previous %}
        <a href="?page={{page_obj.previous_page_number}}" class="text-teal-500">
            <i class="fas fa-arrow-left fa-lg"></i>
        </a>
        {% endif %}

        <span class="mx-3 font-medium text-lg">{{page_obj.number}} of {{page_obj.paginator.num_pages}}</span>

        {% if page_obj.has_next %}
        <a href="?page={{page_obj.next_page_number}}" class="text-teal-500">
            <i class="fas fa-arrow-right fa-lg"></i>
        </a>
        {% endif %}


    </div>
</div>
{% endblock content %}

templates/data/employment_list.html
{% extends "base.html" %}


{% block page_title %}
Home
{% endblock page_title %}

{% block content %}
Test
{% endblock content %}

templates/data/search.html
{% extends "base.html" %}

{% block page_title %}
Search
{% endblock page_title %}

{% block seearch-bar %}
{% endblock seearch-bar %}


{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/2 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        <h2 class="text-xl"> Search!</h2>

        <form method="get" action="{% url "articles:search" %}">
            {{form.as_p}}
            <button class="btn bg-teal-500 mt-5 text-white">Search</button>
        </form>
    </div>
    <div class="container flex flex-col items-center justify-center mx-auto">

        <h2 class="text-xl mx-auto mb-5">Search Results</h2>
        {% for article in articles %}
            {% include 'mixins/article_card.html' with article=article %}
        {% endfor %}
        {% if not articles %}There is nothing matched{% endif %}
    </div>

{% endblock content %}