config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("data/", include("data.urls", namespace="data")),
    path("events/", include("events.urls", namespace="events")),
    path("personnel/", include("personnel.urls", namespace="personnel")),
    path("prediction/", include("prediction.urls", namespace="prediction")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.go_to_home, name="home"),
]

prediction/urls.py
from django.urls import path
from . import views

app_name = "prediction"

urlpatterns = [
    path("", views.PredictionListView.as_view(), name="list",),
    path("summary/", views.PredictionSummaryView.as_view(), name="summary",),
    path("create/", views.PredictionCreateView.as_view(), name="create"),
    path("<int:pk>", views.PredictionDetailView.as_view(), name="detail"),
    path("<int:pk>/edit/", views.predictionEditView.as_view(), name="edit"),
    path("<int:pk>/delete/", views.delete_prediction, name="delete",),
    path("search", views.PredictionSearchView.as_view(), name="search",),
    path("graph", views.update_graph, name="update-graph",),
]

prediction/models.py
from django.db import models
from django.urls import reverse
from core import models as core_models
from data import models as data_models
from users import models as user_models


class RiskType(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class RiskLevel(models.Model):
    name = models.CharField(max_length=255)
    score = models.IntegerField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class Prediction(core_models.TimeStampedModel):

    department = models.ForeignKey(
        data_models.Department,
        related_name="prediction",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
    )
    country = models.ForeignKey(
        data_models.Country, related_name="prediction", on_delete=models.PROTECT
    )
    report_date = models.DateField()

    political_risk = models.ForeignKey(
        RiskLevel,
        verbose_name="정정불안",
        related_name="prediction_political",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
    )
    safety_risk = models.ForeignKey(
        RiskLevel,
        verbose_name="치안",
        related_name="prediction_safety",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
    )
    disaster_risk = models.ForeignKey(
        RiskLevel,
        verbose_name="자연재해",
        related_name="prediction_disaster",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
    )
    medical_risk = models.ForeignKey(
        RiskLevel,
        verbose_name="질병",
        related_name="prediction_medical",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
    )
    other_risk = models.ForeignKey(
        RiskLevel,
        verbose_name="기타",
        related_name="prediction_others",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
    )

    description = models.TextField()
    action = models.TextField()

    author = models.ForeignKey(
        user_models.User,
        related_name="prediction",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
    )

    latest_prediction = models.OneToOneField(
        data_models.Department,
        on_delete=models.PROTECT,
        related_name="latest_prediction",
        null=True,
        blank=True,
    )

    TOTAL_LIST = [
        "political_risk",
        "safety_risk",
        "disaster_risk",
        "medical_risk",
        "other_risk",
    ]

    def get_absolute_url(self):
        return reverse("prediction:detail", kwargs={"pk": self.pk})

    def get_fields(self):
        return [
            (field, RiskLevel.objects.get(pk=field.value_from_object(self)))
            for field in Prediction._meta.fields
            if field.name in Prediction.TOTAL_LIST
        ]

    def get_total_score(self):
        return get_field_sum(Prediction.TOTAL_LIST, self,)


def get_field_sum(x: list, self):
    return sum(
        filter(
            lambda x: x != None,
            [
                RiskLevel.objects.get(pk=field.value_from_object(self)).score
                for field in Prediction._meta.fields
                if field.name in x
            ],
        )
    )

prediction/forms.py
from datetime import datetime
from django import forms
from django_countries.fields import CountryField
from . import models
from users import models as user_models


class PredictionCreateForm(forms.ModelForm):
    class Meta:
        model = models.Prediction
        fields = (
            "country",
            "report_date",
            "political_risk",
            "safety_risk",
            "disaster_risk",
            "medical_risk",
            "other_risk",
            "description",
            "action",
        )
        widgets = {
            "report_date": forms.DateInput(attrs={"placeholder": "YYYY-MM-DD"}),
            "description": forms.Textarea(attrs={"placeholder": "안전전망"}),
            "action": forms.Textarea(attrs={"placeholder": "조치사항"}),
        }

    def __init__(self, user, *args, **kwargs):
        # 인자를 받기 위해서는 view에서 get_from_kwargs를 정의하고 super를 통해서 user 값을 확보해야 한다.
        super(PredictionCreateForm, self).__init__(*args, **kwargs)
        print(user, user.department)
        if user.department:
            country_choice = (
                user.department.department_detail.filter()
                .order_by("-created")[0]
                .countries.all()
            )
            print(list(((i, i.korean) for i in country_choice)))
            self.fields["country"].choices = ((i.id, i.korean) for i in country_choice)
        else:
            country_choice = (None, None)
            self.fields["country"].choices = ((i.id, i.korean) for i in country_choice)
        self.fields["report_date"].initial = datetime.now()

    def save(self, *args, **kwargs):
        prediction = super().save(commit=False)
        return prediction


class SearchForm(forms.ModelForm):
    class Meta:
        model = models.Prediction
        fields = (
            "country",
            "report_date",
            "political_risk",
            "safety_risk",
            "disaster_risk",
            "medical_risk",
            "other_risk",
        )

    def __init__(self, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].required = False

prediction/views.py
import pandas as pd
from django.http import Http404
from django.views.generic import ListView, DetailView, View, UpdateView, FormView
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, redirect, reverse
from django.core.paginator import Paginator
from django.core.exceptions import ObjectDoesNotExist
from django_countries import countries
from users import mixins as user_mixins
from data import models as data_models
from . import models, forms
from plotly_graph import plot_prediction


class PredictionCreateView(user_mixins.LoggedInOnlyView, FormView):

    form_class = forms.PredictionCreateForm
    template_name = "prediction/prediction_create.html"

    def get_form_kwargs(self):
        kwargs = super(PredictionCreateView, self).get_form_kwargs()
        user = self.request.user
        kwargs["user"] = user
        return kwargs

    def form_valid(self, form):
        prediction = form.save()
        prediction.author = self.request.user
        prediction.department = self.request.user.department
        try:
            print(self.request.user.department.latest_prediction)
            self.request.user.department.latest_prediction.latest_prediction_id = None
            self.request.user.department.latest_prediction.save()
        except ObjectDoesNotExist:
            pass
        prediction.latest_prediction = self.request.user.department
        prediction.save()
        return redirect(reverse("prediction:detail", kwargs={"pk": prediction.pk}))


class PredictionDetailView(user_mixins.LoggedInOnlyView, DetailView):
    model = models.Prediction


class predictionEditView(user_mixins.LoggedInOnlyView, UpdateView):
    model = models.Prediction
    template_name = "prediction/prediction_edit.html"
    fields = (
        "country",
        "political_risk",
        "safety_risk",
        "disaster_risk",
        "medical_risk",
        "other_risk",
        "description",
        "action",
    )

    def get_object(self, queryset=None):
        prediction = super().get_object(queryset=queryset)
        if prediction.author.pk != self.request.user.pk:
            raise Http404()

        return prediction


@login_required
def delete_prediction(request, pk):
    user = request.user
    try:
        prediction = models.Prediction.objects.get(pk=pk)
        if prediction.author.pk != user.pk:
            messages.error(request, "Can't delete that prediction")
        else:
            models.Prediction.objects.filter(pk=pk).delete()
            messages.success(request, "Prediction Deleted")
        return redirect((reverse("core:home")))
    except models.Prediction.DoesNotExist:
        return redirect((reverse("core:home")))


class PredictionSearchView(user_mixins.LoggedInOnlyView, View):
    def get(self, request):

        form = forms.SearchForm(request.GET)

        if form.is_valid():

            country = form.cleaned_data.get("country")
            report_date = form.cleaned_data.get("report_date")
            political_risk = form.cleaned_data.get("political_risk")
            safety_risk = form.cleaned_data.get("safety_risk")
            disaster_risk = form.cleaned_data.get("disaster_risk")
            medical_risk = form.cleaned_data.get("medical_risk")
            other_risk = form.cleaned_data.get("other_risk")

            filter_args = {}

            if country:
                filter_args["country"] = country

            if report_date:
                filter_args["report_date"] = report_date

            if political_risk:
                filter_args["political_risk"] = political_risk

            if safety_risk:
                filter_args["safety_risk"] = safety_risk

            if disaster_risk:
                filter_args["disaster_risk"] = disaster_risk

            if medical_risk:
                filter_args["medical_risk"] = medical_risk

            if other_risk:
                filter_args["other_risk"] = other_risk

            qs = models.Prediction.objects.filter(**filter_args).order_by("-created")

            paginator = Paginator(qs, 10, orphans=5)

            page = request.GET.get("page", 1)

            prediction = paginator.get_page(page)

            return render(
                request,
                "prediction/search.html",
                {"form": form, "prediction": prediction},
            )

        else:

            form = forms.SearchForm()

            return render(request, "prediction/search.html", {"form": form})


class PredictionListView(user_mixins.LoggedInOnlyView, ListView):
    model = models.Prediction
    context_object_name = "prediction"
    template_name = "personnel/prediction_list.html"
    paginate_by = 24
    paginate_orphans = 5
    ordering = ["-created"]


class PredictionSummaryView(user_mixins.LoggedInOnlyView, ListView):
    model = data_models.Department
    ordering = "pk"
    context_object_name = "departments"
    template_name = "prediction/prediction_summary.html"

    def get_context_data(self, **kwargs):
        context = super(PredictionSummaryView, self).get_context_data(**kwargs)
        return context


def update_graph(request):
    df = get_data_frame()
    plot_prediction(df)
    return redirect((reverse("prediction:summary")))


def get_data_frame():

    # read query
    df = pd.DataFrame(
        list(
            data_models.Department.objects.exclude(
                latest_prediction__id=None
            ).values_list(
                "latest_prediction__country__code",
                "latest_prediction__country__korean",
                "latest_prediction__report_date",
                "latest_prediction__political_risk__score",
                "latest_prediction__safety_risk__score",
                "latest_prediction__disaster_risk__score",
                "latest_prediction__medical_risk__score",
                "latest_prediction__other_risk__score",
            )
        ),
        columns=[
            "code",
            "country",
            "report_date",
            "political_risk",
            "safety_risk",
            "disaster_risk",
            "medical_risk",
            "other_risk",
        ],
    )
    # data processing
    df["total_score"] = df.sum(axis=1)
    df["location_situation"] = (
        df["country"]
        + " | "
        + df["report_date"].apply(str)
        + " | "
        + df["total_score"].apply(str)
    )
    df["location_code"] = df["code"].apply(countries.alpha3)
    return df

templates/prediction/prediction_create.html
{% extends "base.html" %}

{% block page_title %}
Risk prediction create
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}
{% block content %}



<div class="container lg:w-5/12 md:w-1/2 xl:w-1/2 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

    {% include 'mixins/article/article_form.html' with form=form cta="Create Article" %}

</div>
{% endblock content %}

templates/prediction/prediction_detail.html
{% extends "base.html" %}

{% block page_title %}
{{article.title}}
{% endblock page_title %}

{% block content %}

<div class="container mx-auto flex justify-around pb-10">
    <div class="lg:w-1/2 md:w-3/4 px-5">
        <div class="flex w-full justify-between border-section">
            <div class="pb-1 content-around">
                <div class="flex justify-between box-border">
                    <h4 class="text-3xl font-medium h-full">{{prediction.title}}</h4>
                </div>
                <div class="justify-between w-full overflow-hidden ">
                    <span class="text-gray-700 font-bold">{{prediction.country.name}}</span>
                    <span class="text-teal-800 font-bold px-5">위험도 {{prediction.get_total_score}}</span>
                </div>
                <div>
                    <span class="text-sm text-gray-500 font-bold">{{prediction.report_date}}</span>
                </div>
                <div class="flex">
                    {% for field, value in prediction.get_fields %}
                    <div>
                        <span class="mr-5 text-gray-700 font-bold">{{field.verbose_name}}</span>
                        <span
                            class="mr-5 {% if value.pk == 1 %} text-red-600 {% elif value.pk == 2 %} text-orange-300 {%else%} text-green-300{% endif %} font-bold">{{value}}</span>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div>
                <a href="{{prediction.author.get_absolute_url}}" class="flex flex-col items-center">
                    {% include "mixins/user_avatar.html" with user=prediction.author %}
                    <span class="mt-2 text-gray-500">{{prediction.author.first_name}}</span>
                </a>
            </div>
        </div>
        <div class="border-section">
            <p class="w-full p-3">
                {{prediction.description|linebreaks}}
            </p>
        </div>
        <div class="border-section">
            <p class="w-full p-3">
                {{prediction.action|linebreaks}}
            </p>
        </div>
        {% if user == prediction.author %}
        <div class="flex flex-col w-full">
            <a href="{% url 'prediction:edit' prediction.pk %}" class="btn-link bg-teal-500 mb-3">Edit prediction</a>
            <a href="{% url 'prediction:delete' prediction.pk %}" class="btn-link">Delete prediction</a>
        </div>
        {% endif %}
    </div>
</div>

{% endblock content %}

templates/prediction/prediction_edit.html
{% extends "base.html" %}

{% block page_title %}
Update Prediction
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="container lg:w-5/12 md:w-1/4 mx-auto my-10 flex flex-col itmes-center border p-6 border-gray-400">

    {% include "mixins/article/article_form.html" with form=form cta="Update Prediction" %}

</div>

{% endblock content %}

templates/prediction/prediction_list.html
{% extends "base.html" %}


{% block page_title %}
안전전망 목록
{% endblock page_title %}

{% block content %}

<div class="container mx-auto pb-10">
    <div class="justify-center flex mb-3">
        <div class='w-1/4 flex'>
            <a href="{% url 'prediction:create' %}" class="btn bg-red-500 my-0 mx-3 text-white">신규작성</a>
        </div>
    </div>
    <div class="flex flex-wrap justify-center mb-10">
        {% for predict in prediction %}
        {% include 'mixins/prediction/predict_card.html' with predict=predict %}
        {% endfor %}
    </div>
    <div class="flex items-center justify-center mx-auto container">
        {% if page_obj.has_previous %}
        <a href="?page={{page_obj.previous_page_number}}" class="text-teal-500">
            <i class="fas fa-arrow-left fa-lg"></i>
        </a>
        {% endif %}

        <span class="mx-3 font-medium text-lg">{{page_obj.number}} of {{page_obj.paginator.num_pages}}</span>

        {% if page_obj.has_next %}
        <a href="?page={{page_obj.next_page_number}}" class="text-teal-500">
            <i class="fas fa-arrow-right fa-lg"></i>
        </a>
        {% endif %}


    </div>
</div>

{% endblock content %}

templates/prediction/prediction_summary.html
{% extends "base.html" %}


{% block page_title %}
안전예보
{% endblock page_title %}

{% block content %}

<div class="container mx-auto pb-10 justify-center">
    <div class="justify-between flex mb-3">
        <div class='w-1/2 flex'>
            <a href="{% url 'prediction:create' %}" class="btn bg-red-500 my-0 mx-3 text-white">신규작성</a>
        </div>
        <div class='w-1/2 flex'>
            <a href="{% url 'prediction:update-graph' %}" class="btn my-0 mx-3 text-red-500 font-bold">그래프 갱신</a>
            <a href="{% url 'prediction:list' %}" class="btn my-0 mx-3 text-red-500 font-bold">목록보기</a>
        </div>
    </div>

    <div class="rounded-xl border overflow-hidden mb-3">{% include 'mixins/prediction_graph.html' %}</div>

    <div>
        <table class="table-fixed block mx-auto">
            <tbody class="block">
                <tr>
                    <th class="border p-2  text-center xl:truncate font-medium">사무소명</th>
                    <th class="border p-2  text-center xl:truncate font-medium">보고일</th>
                    <th class="border p-2  text-center xl:truncate font-medium">정정불안</th>
                    <th class="border p-2  text-center xl:truncate font-medium">치안</th>
                    <th class="border p-2  text-center xl:truncate font-medium">자연재해</th>
                    <th class="border p-2  text-center xl:truncate font-medium">질병</th>
                    <th class="border p-2  text-center xl:truncate font-medium">기타</th>
                    <th class="border p-2  text-center font-medium">안전전망</th>
                    <th class="border p-2  text-center font-medium">조치사항</th>
                </tr>
                {% for department in departments %}
                {% if department.is_active %}
                <tr>
                    <td class="border p-2  text-center xl:truncate"><a
                            href="{% url 'prediction:detail' department.latest_prediction.pk %}"
                            class="text-teal-500 font-bold">{{department.name}}</a></td>
                    <td class="border p-2  text-center xl:truncate">
                        {{department.get_latest_prediction.report_date|date:"m-d"}}
                    </td>
                    <td class="border p-2  text-center xl:truncate">
                        {{department.get_latest_prediction.political_risk|default_if_none:"-"}}</td>
                    <td class="border p-2  text-center xl:truncate">
                        {{department.get_latest_prediction.safety_risk|default_if_none:"-"}}</td>
                    <td class="border p-2  text-center xl:truncate">
                        {{department.get_latest_prediction.disaster_risk|default_if_none:"-"}}</td>
                    <td class="border p-2  text-center xl:truncate">
                        {{department.get_latest_prediction.medical_risk|default_if_none:"-"}}</td>
                    <td class="border p-2  text-center xl:truncate">
                        {{department.get_latest_prediction.other_risk|default_if_none:"-"}}</td>
                    <td class="border p-2 ">{{department.get_latest_prediction.description|linebreaks}}</td>
                    <td class="border p-2 ">{{department.get_latest_prediction.action|linebreaks}}</td>
                </tr>
                {% endif %}

                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock content %}

templates/prediction/search.html
{% extends "base.html" %}

{% block page_title %}
Search
{% endblock page_title %}

{% block seearch-bar %}
{% endblock seearch-bar %}


{% block content %}

<div class="container lg:w-5/12 md:w-1/2 xl:w-1/2 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
    <h2 class="text-xl"> Search!</h2>

    <form method="get" action="{% url "prediction:search" %}" class="flex, flex-wrap">
        {{form.as_p}}
        <button class="btn bg-teal-500 mt-5 text-white">Search</button>
    </form>
</div>
<div class="container flex flex-col items-center justify-center mx-auto">

    <h2 class="text-xl mx-auto mb-5">Search Results</h2>
    {% for article in articles %}
    {% include 'mixins/article_card.html' with article=article %}
    {% endfor %}
    {% if not articles %}There is nothing matched{% endif %}
</div>

{% endblock content %}