config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("data/", include("data.urls", namespace="data")),
    path("events/", include("events.urls", namespace="events")),
    path("personnel/", include("personnel.urls", namespace="personnel")),
    path("prediction/", include("prediction.urls", namespace="prediction")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.go_to_home, name="home"),
]

events/urls.py
from django.urls import path
from . import views

app_name = "events"

urlpatterns = [
    path("list/", views.EventListView.as_view(), name="list",),
    path("create/", views.EventCreateView.as_view(), name="create"),
    path("<int:pk>", views.EventDetailView.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EventEditView.as_view(), name="edit"),
    path("<int:pk>/delete/", views.delete_event, name="delete",),
    path("search", views.EventSearchView.as_view(), name="search",),
]

events/models.py
from datetime import datetime
from django.db import models
from django.urls import reverse
from core import models as core_models
from users import models as user_models
from data import models as data_models

# Create your models here.


class EventType(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class Event(core_models.TimeStampedModel):

    title = models.CharField(max_length=255)
    country = models.ForeignKey(
        data_models.Country, related_name="events", on_delete=models.PROTECT
    )
    event_type = models.ForeignKey(
        EventType, related_name="events", on_delete=models.PROTECT
    )
    start_date = models.DateField()
    end_date = models.DateField()
    description = models.TextField()
    is_single = models.BooleanField(verbose_name="One day", default=True)

    author = models.ForeignKey(
        user_models.User,
        related_name="events",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
    )
    department = models.ForeignKey(
        data_models.Department,
        related_name="events",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
    )

    def get_absolute_url(self):
        return reverse("events:detail", kwargs={"pk": self.pk})

events/forms.py
from datetime import datetime
from django import forms
from django_countries.fields import CountryField
from . import models
from users import models as user_models


class EventCreateForm(forms.ModelForm):

    country = forms.ChoiceField(required=True)

    class Meta:
        model = models.Event
        fields = (
            "title",
            "country",
            "event_type",
            "is_single",
            "start_date",
            "end_date",
            "description",
        )
        widgets = {
            "title": forms.TextInput(attrs={"placeholder": "제목"}),
            "start_date": forms.DateInput(attrs={"placeholder": "YYYY-MM-DD"}),
            "end_date": forms.DateInput(attrs={"placeholder": "YYYY-MM-DD"}),
            "description": forms.Textarea(attrs={"placeholder": "세부내역"}),
        }

    def __init__(self, user, *args, **kwargs):
        # 인자를 받기 위해서는 view에서 get_from_kwargs를 정의하고 super를 통해서 user 값을 확보해야 한다.
        super(EventCreateForm, self).__init__(*args, **kwargs)
        if user.department:
            country_choice = (
                user.department.department_detail.filter()
                .order_by("-created")[0]
                .countries.all()
            )
            self.fields["country"].choices = (
                (i.code, i.korean) for i in country_choice
            )
        else:
            self.fields["country"].choices = (("None", "없음"),)
        self.fields["start_date"].initial = datetime.now()
        self.fields["end_date"].initial = datetime.now()
        self.fields["is_single"].initial = True

    def save(self, *args, **kwargs):
        event = super().save(commit=False)
        return event


class SearchForm(forms.ModelForm):
    class Meta:
        model = models.Event
        fields = (
            "title",
            "country",
            "event_type",
        )

    def __init__(self, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].required = False

events/views.py
from django.http import Http404
from django.views.generic import ListView, DetailView, View, UpdateView, FormView
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, redirect, reverse
from django.core.paginator import Paginator
from users import mixins as user_mixins
from . import models, forms


class EventCreateView(user_mixins.LoggedInOnlyView, FormView):

    form_class = forms.EventCreateForm
    template_name = "events/event_create.html"

    def get_form_kwargs(self):
        kwargs = super(EventCreateView, self).get_form_kwargs()
        user = self.request.user
        kwargs["user"] = user
        return kwargs

    def form_valid(self, form):
        event = form.save()
        event.author = self.request.user
        event.department = self.request.user.department
        if event.is_single:
            event.end_date = event.start_date
        event.save()
        return redirect(reverse("events:detail", kwargs={"pk": event.pk}))


class EventDetailView(DetailView):
    model = models.Event


class EventEditView(UpdateView):
    model = models.Event
    template_name = "events/event_edit.html"
    fields = (
        "title",
        "country",
        "event_type",
        "start_date",
        "end_date",
        "description",
    )

    def get_object(self, queryset=None):
        event = super().get_object(queryset=queryset)
        if event.author.pk != self.request.user.pk:
            raise Http404()

        return event


@login_required
def delete_event(request, pk):
    user = request.user
    try:
        event = models.Event.objects.get(pk=pk)
        if event.author.pk != user.pk:
            messages.error(request, "Can't delete that Event")
        else:
            models.Event.objects.filter(pk=pk).delete()
            messages.success(request, "Event Deleted")
        return redirect((reverse("core:home")))
    except models.Event.DoesNotExist:
        return redirect((reverse("core:home")))


class EventListView(ListView):

    model = models.Event
    paginate_by = 12
    paginate_orphans = 5
    ordering = "created"
    context_object_name = "events"


class EventSearchView(View):
    def get(self, request):

        form = forms.SearchForm(request.GET)

        if form.is_valid():

            title = form.cleaned_data.get("title")
            country = form.cleaned_data.get("country")
            event_type = form.cleaned_data.get("event_type")

            filter_args = {}

            if title:
                filter_args["title__contains"] = title

            if country:
                filter_args["country"] = country

            if event_type:
                filter_args["event_type"] = event_type

            qs = models.Event.objects.filter(**filter_args).order_by("-created")

            paginator = Paginator(qs, 10, orphans=5)

            page = request.GET.get("page", 1)

            event = paginator.get_page(page)

            return render(
                request, "events/search.html", {"form": form, "event": event},
            )

        else:

            form = forms.SearchForm()

            return render(request, "events/search.html", {"form": form})

templates/events/event_create.html
{% extends "base.html" %}

{% block page_title %}
Events create
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}
{% block content %}



<div class="container lg:w-5/12 md:w-1/2 xl:w-1/2 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

    {% include 'mixins/article/article_form.html' with form=form cta="Create Article" %}

</div>
{% endblock content %}

templates/events/event_detail.html
{% extends "base.html" %}

{% block page_title %}
{{event.title}}
{% endblock page_title %}

{% block content %}

<div class="container mx-auto flex justify-around pb-10">
    <div class="lg:w-1/2 md:w-3/4 px-5">
        <div class="flex w-full justify-between border-section">
            <div class="pb-1 content-around">
                <div class="flex justify-between box-border">
                    <h4 class="text-3xl font-medium h-full">{{event.title}}</h4>
                </div>
                <div class="justify-between w-full overflow-hidden ">
                    <span class="text-gray-700 font-bold">{{event.country.name}}</span>
                    <span class="text-teal-800 font-bold px-5">{{event.event_type}}</span>
                </div>
                <div>
                    <span class="text-sm text-gray-500 font-bold">{{prediction.start_date}}</span>
                    <span class="text-sm text-gray-500 font-bold">{{prediction.end_date}}</span>
                </div>
            </div>
            <div>
                <a href="{{prediction.author.get_absolute_url}}" class="flex flex-col items-center">
                    {% include "mixins/user_avatar.html" with user=prediction.author %}
                    <span class="mt-2 text-gray-500">{{prediction.author.first_name}}</span>
                </a>
            </div>
        </div>
        <div class="border-section">
            <p class="w-full p-5">
                {{event.description|linebreaks}}
            </p>
        </div>
        {% if user == event.author %}
        <div class="flex flex-col w-full">
            <a href="{% url 'events:edit' event.pk %}" class="btn-link bg-teal-500 mb-3">Edit event</a>
            <a href="{% url 'events:delete' event.pk %}" class="btn-link">Delete event</a>
        </div>
        {% endif %}
    </div>
</div>

{% endblock content %}

templates/events/event_edit.html
{% extends "base.html" %}

{% block page_title %}
Update Prediction
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="container lg:w-5/12 md:w-1/4 mx-auto my-10 flex flex-col itmes-center border p-6 border-gray-400">

    {% include "mixins/article/article_form.html" with form=form cta="Update Prediction" %}

</div>

{% endblock content %}

templates/events/event_list.html
{% extends "base.html" %}


{% block page_title %}
주요일정 정보
{% endblock page_title %}

{% block content %}

<div class="container mx-auto pb-10">
    <div class="justify-between flex mb-3">
        <div class='w-1/2 flex'>
            <a href="{% url 'events:create' %}" class="btn bg-red-500 my-0 mx-3 text-white">신규작성</a>
        </div>
        <div class='w-full align-middle'>
            <div>
                <form method="get" action="{% url "events:search" %}" class="w-9/12 inline-block align-middle">
                    <input
                        class="search-box border inline-block align-middle px-5 w-full font-medium text-gray-900 placeholder-gray-600 py-3 rounded-sm w-64 shadow-md hover:shadow-lg focus:outline-none"
                        name="title" placeholder="Search by Title" />
                </form>
            </div>
        </div>
    </div>
    <div class="flex flex-wrap justify-center mb-10">
        {% for event in events %}
        {% include 'mixins/events/event_card.html' with event=event %}
        {% endfor %}
    </div>
    <div class="flex items-center justify-center mx-auto container">
        {% if page_obj.has_previous %}
        <a href="?page={{page_obj.previous_page_number}}" class="text-teal-500">
            <i class="fas fa-arrow-left fa-lg"></i>
        </a>
        {% endif %}

        <span class="mx-3 font-medium text-lg">{{page_obj.number}} of {{page_obj.paginator.num_pages}}</span>

        {% if page_obj.has_next %}
        <a href="?page={{page_obj.next_page_number}}" class="text-teal-500">
            <i class="fas fa-arrow-right fa-lg"></i>
        </a>
        {% endif %}


    </div>
</div>

{% endblock content %}

templates/events/search.html
{% extends "base.html" %}

{% block page_title %}
Search
{% endblock page_title %}

{% block seearch-bar %}
{% endblock seearch-bar %}


{% block content %}

<div class="container lg:w-5/12 md:w-1/2 xl:w-1/2 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
    <h2 class="text-xl"> Search!</h2>

    <form method="get" action="{% url "events:search" %}">
        {{form.as_p}}
        <button class="btn bg-teal-500 mt-5 text-white">Search</button>
    </form>
</div>
<div class="container flex flex-col items-center justify-center mx-auto">

    <h2 class="text-xl mx-auto mb-5">Search Results</h2>
    {% for event in events %}
    {% include 'mixins/events_card.html' with event=event %}
    {% endfor %}
    {% if not events %}There is nothing matched{% endif %}
</div>

{% endblock content %}